samples: utils: build: cmake: fix compile errors
fix "undefined reference to dlopen'"

update to 1.10.0_[8]

Change-Id: I683c03c657af5b0bc93bee97f9d57a15acb5947f
Signed-off-by: Yu Qiaowei <cerf.yu@rock-chips.com>